name: create_package_workflow
on:
  workflow_dispatch:
jobs:
  main_sfdx_ci:
    runs-on: ubuntu-latest
    name: Create Package Version
    steps:
      - name: Checkout Repository Main Branch
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{  secrets.AWS_REGION }}
      - name: Login to AWS ECR
        id: login-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Run Container
        id: createpkg
        uses: ./config/workflow/run-container-ecr # Uses an action in the specified directory
        env:
          DEV_HUB_URL: ${{ secrets.DEV_HUB }}
          BRANCH: ${{ github.ref }}
          SCRIPTS_PATH: /github/workspace
          ECR_REGISTRY: ${{ steps.login-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: sfdxdocker
          IMAGE_TAG: latest
        # pass input parameter
        with:
          operation: create_version
          imageurl: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      