name: Create Package Workflow
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  main_sfdx_ci:
    runs-on: ubuntu-latest
    name: Create Package Version
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout Repository Main Branch
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create Package Version
        uses: ./config/workflow # Uses an action in the specified directory
        env:
          DEV_HUB_URL: ${{ secrets.DEV_HUB }}
          BRANCH: ${{ github.ref }}
          SCRIPTS_PATH: /github/workspace
        # pass input parameter
        with:
          operation: create_version
      - name: Send Notification
        env:
          SCRIPTS_PATH: /github/workspace
        if: ${{ failure() }}
        shell: bash
        run: ./config/scripts/ci/sendNotification.sh