name: Create Package Version
on:
  #push:
    #branches: [ main ]
  workflow_dispatch:
jobs:
  main_sfdx_ci:
    runs-on: ubuntu-latest
    name: Create Package Version
    steps:
      # checkout the repository
      - name: Checkout Repository Main Branch
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      # configure aws variables
      - name: Configure container registry
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # login to container registry
      - name: Login to container registry
        id: login-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
      # create package version
      - name: Create Package Version
        id: createpkg
        uses: ./config/workflow/run-container # Uses an action in the specified directory
        env:
          DEV_HUB_URL: ${{ secrets.DEV_HUB }}
          BRANCH: ${{ github.ref }}
          LATEST_COMMIT: ${{ github.sha }}
          SCRIPTS_PATH: /operation/workspace
          IMAGE_NAME: dockerdx:latest
        # pass input parameter
        with:
          # operation to perform
          operation: create_version
          # url to pull image
          imageurl: ${{ steps.login-aws-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}
      # send notification on step failure
      - name: Send Notification
        env:
          SCRIPTS_PATH: .
        if: ${{ failure() }}
        shell: bash
        run: ./config/scripts/ci/sendNotification.sh
      