on:
  workflow_run:
    workflows:
      - Create Package Version
    types: 
      - completed
  workflow_dispatch:
jobs:
  install_dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository Main Branch
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: main
          submodules: true
      - name: Install package in dev environment
        id: install_dev
        uses: ./config/workflow/run-container # Uses an action in the specified directory
        env:
          DEV_HUB_URL: ${{ secrets.DEV_HUB }}
          ENV_URL: ${{ secrets.DEV_ENV }}
          SCRIPTS_PATH: /operation/workspace
        # pass input parameter
        with:
          operation: install_version
  install_ci:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository Main Branch
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: main
          submodules: true
      - name: Install package in ci environment
        id: install_ci
        uses: ./config/workflow/run-container # Uses an action in the specified directory
        env:
          DEV_HUB_URL: ${{ secrets.DEV_HUB }}
          ENV_URL: ${{ secrets.CI_ENV }}
          SCRIPTS_PATH: /operation/workspace
        # pass input parameter
        with:
          operation: install_version
  install_sit:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository Main Branch
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: main
          submodules: true
      - name: Install package in sit environment
        id: install_sit
        uses: ./config/workflow/run-container # Uses an action in the specified directory
        env:
          DEV_HUB_URL: ${{ secrets.DEV_HUB }}
          ENV_URL: ${{ secrets.SIT_ENV }}
          SCRIPTS_PATH: /operation/workspace
        # pass input parameter
        with:
          operation: install_version