name: Main Workflow
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  main_sfdx_ci:
    runs-on: ubuntu-latest
    name: Run SFDX
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout Repository Main Branch
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Call action from config repo
        uses: ./config/workflow # Uses an action in the specified directory
        env:
          DEV_HUB_URL: ${{ secrets.DEV_HUB }}
        # pass input parameter
        with:
          dev-hub: ${{ secrets.DEV_HUB }}
          operation: create_version