on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run SFDX
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Test config
        run: echo ${{secrets.DEV_HUB}}
      - name: Call action from config repo
        uses: ./config/testfolder # Uses an action in the specified directory
        id: hello
        # pass input parameter
        #with:
          #param1: 'Super'
      # Use the output from the `hello` step
      #- name: Get the output time
        #run: echo "The time was ${{ steps.hello.outputs.time }}"
