name: Test Workflow
on:
  workflow_dispatch:
jobs:
  run_main:
    runs-on: ubuntu-latest
    name: Test run
    steps:
       - name: Checkout Repository Main Branch
         id: checkout
         uses: actions/checkout@v2
         with:
          ref: main
          submodules: true
       - name: composite step
         id: createpkg
         uses: ./config/workflow/test/
        #shell: bash
        #run: echo "Workflow Run Completed"