name: Test_Workflow
on:
  workflow_dispatch:
jobs:
  run_main:
    runs-on: ubuntu-latest
    name: Test run
    steps:
      - name: Checkout Repository Main Branch
        id: run_bash
        shell: bash
        run: echo "Workflow Run Completed"