name: Test Workflow
on:
  workflow_dispatch:
jobs:
  run_main:
    runs-on: ubuntu-latest
    name: Test run
    steps:
       - name: Checkout Repository Main Branch
         id: checkout
         uses: actions/checkout@v2
         with:
          ref: main
          submodules: true
       - name: composite step
         id: createpkg
         uses: ./config/test/
       - name: check output
         id: chkop
         shell: bash
         run: echo ${{ steps.createpkg.outputs.output_step_var }}
       - name: Repo
         id: Repo
         shell: bash
         run: echo $GITHUB_REPOSITORY
       - name: Workspace
         id: Workspace
         shell: bash
         run: echo $GITHUB_WORKSPACE
        